### ISSUE TITLE
报错信息

### ISSUE THREAD

**Issue by Crys-Chen** [chenluda/zhihu-download#12]
* Running on http://127.0.0.1:5000
Press CTRL+C to quit
127.0.0.1 - - [06/Mar/2024 11:00:27] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [06/Mar/2024 11:00:27] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [06/Mar/2024 11:00:27] "GET /favicon.ico HTTP/1.1" 404 -
[2024-03-06 11:00:41,260] ERROR in app: Exception on / [POST]
Traceback (most recent call last):
  File "D:\Software\Anaconda\envs\auto\lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\Software\Anaconda\envs\auto\lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\Software\Anaconda\envs\auto\lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\Software\Anaconda\envs\auto\lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\Winter\Desktop\Auto\blog2md\zhihu2md\new\zhihu-download-main\app.py", line 21, in index
    markdown_title = judge_zhihu_type(url)
  File "C:\Users\Winter\Desktop\Auto\blog2md\zhihu2md\new\zhihu-download-main\main.py", line 81, in judge_zhihu_type
    title = parse_zhihu_article(url, hexo_uploader)
  File "C:\Users\Winter\Desktop\Auto\blog2md\zhihu2md\new\zhihu-download-main\main.py", line 260, in parse_zhihu_article
    author = soup.select_one('div.AuthorInfo').find(
AttributeError: 'NoneType' object has no attribute 'find'
127.0.0.1 - - [06/Mar/2024 11:00:41] "POST / HTTP/1.1" 500 -

**Comment by chenluda** [comment]
Dear Crys-Chen: @Crys-Chen 

您好！非常感谢您提出的问题！

请问可以发下报错的知乎链接吗，这对我们寻找 bug 至关重要，谢谢！

Sincerely,
Luda Chen
Email: [chenluda01@gmail.com](mailto:chenluda01@gmail.com)

**Comment by McfhHolmes0** [comment]
我出现了同样的问题，变量soup的部分结果是："知乎 - 有问题，就会有答案</p><p class="Unhuman-tip">系统监测到您的网络环境存在异常风险，为保证您的正常访问，请输入验证码进行验证。"
但是我重启电脑以后，程序就可以正常使用了，遗憾的是只能使用一次，用第二次就会出现同样的错误，这是什么原因？

**Comment by Afterimages** [comment]
@McfhHolmes0 
在发送get请求时加一个header和cookie就可以了

**Comment by chenluda** [comment]
@McfhHolmes0 @Crys-Chen @Afterimages ：

主要原因是知乎最新的反爬机制，在未登录状态下爬取数据会触发验证，
就如 @Afterimages A 神所说的，在请求头中加入登录知乎后的 cookie 就可以了，
如何获取知乎 cookie 可以参考 [这里](http://8.130.108.230:5000/get-cookies)，
代码已经更新，并且已经部署，可以直接访问 [演示网站](http://8.130.108.230:5000) 操作。
@Afterimages  A 神有空看下是否合理 :)

Sincerely,
Luda Chen
Email: [chenluda01@gmail.com](mailto:chenluda01@gmail.com)

**Comment by Afterimages** [comment]
@chenluda C神速度真快
