### ISSUE TITLE
KeyError: 'href'

### ISSUE THREAD

**Issue by NoaneWang** [chenluda/zhihu-download#13]
在保存https://www.zhihu.com/question/362131975/answer/2182682685 时出现以下报错：
Traceback (most recent call last):
  File "D:\anaconda3\Lib\site-packages\flask\app.py", line 2529, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\anaconda3\Lib\site-packages\flask\app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\anaconda3\Lib\site-packages\flask\app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\anaconda3\Lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\wyt\Downloads\zhihu-download-main\app.py", line 21, in index
    markdown_title = judge_zhihu_type(url)
                     ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\wyt\Downloads\zhihu-download-main\main.py", line 77, in judge_zhihu_type
    title = parse_zhihu_answer(url, hexo_uploader)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\wyt\Downloads\zhihu-download-main\main.py", line 286, in parse_zhihu_answer
    markdown_title = save_and_transform(
                     ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\wyt\Downloads\zhihu-download-main\main.py", line 157, in save_and_transform
    original_url = link['href']
                   ~~~~^^^^^^^^
  File "D:\anaconda3\Lib\site-packages\bs4\element.py", line 1573, in __getitem__
    return self.attrs[key]
           ~~~~~~~~~~^^^^^
KeyError: 'href'
127.0.0.1 - - [11/Mar/2024 16:18:49] "POST / HTTP/1.1" 500 -

**Comment by chenluda** [comment]
Dear Wang:

感谢您提出问题！

这个问题出现的原因是知乎的排版的调整，导致原有代码无法正常解析链接。

我们已经根据最新的排版更新了代码，如有问题，请您随时联系我们，谢谢！

Sincerely,
Luda Chen
Email: [chenluda01@gmail.com](mailto:chenluda01@gmail.com)
2024-03-14 10:53:40
